from enum import Enum, auto

class TokenType (Enum):
    
    LXR_WHITESPACE = auto()
    LXR_COMMENT = auto()

    LXR_IDENT = auto()
    LXR_NATURAL = auto()
    LXR_FLOAT = auto()
    LXR_STRING = auto()
    LXR_BOOLEAN = auto()
    
    LXR_NULL = auto()
    LXR_NULLID = auto()

    LXR_CAST = auto()
    LXR_LOG = auto()
    LXR_WAIT = auto()
    LXR_SLEEP = auto()
    LXR_ASSERT = auto()
    LXR_TUNINGSTART = auto()
    LXR_TUNINGMARK = auto()
    LXR_TUNINGEND = auto()
    LXR_TRANSLATE = auto()
    LXR_DUMP = auto()
    LXR_DUMPTYPE = auto()
    
    LXR_STRING_AND_CONCAT = auto()
    LXR_CONCAT_AND_STRING = auto()
    LXR_CONCAT_AND_STRING_AND_CONCAT = auto()
    
    LXR_BRACKET_ROUND_OP = auto()
    LXR_BRACKET_ROUND_CL = auto()
    LXR_BRACKET_CURLY_OP = auto()
    LXR_BRACKET_CURLY_CL = auto()
    LXR_BRACKET_SQUARE_OP = auto()
    LXR_BRACKET_SQUARE_CL = auto()
    
    LXR_KEYWORD_MAIN = auto()
    LXR_KEYWORD_IF = auto()
    LXR_KEYWORD_ELSE = auto()
    LXR_KEYWORD_WHILE = auto()
    LXR_KEYWORD_FOR = auto()
    LXR_KEYWORD_FOREACH = auto()
    LXR_KEYWORD_SWITCH = auto()
    LXR_KEYWORD_SWITCHTYPE = auto()
    LXR_KEYWORD_CASE = auto()
    LXR_KEYWORD_DEFAULT = auto()
    LXR_KEYWORD_YIELD = auto()
    LXR_KEYWORD_CONTINUE = auto()
    LXR_KEYWORD_BREAK = auto()
    LXR_KEYWORD_RETURN = auto()
    LXR_KEYWORD_IS = auto()
    LXR_KEYWORD_AS = auto()
    LXR_KEYWORD_IN = auto()
    LXR_KEYWORD_DECLARE = auto()
    
    LXR_TYPE_CLASS = auto()
    LXR_TYPE_VOID = auto()
    LXR_TYPE_INTEGER = auto()
    LXR_TYPE_REAL = auto()
    LXR_TYPE_TEXT = auto()
    LXR_TYPE_BOOLEAN = auto()
    LXR_TYPE_IDENT = auto()
    LXR_TYPE_INT2 = auto()
    LXR_TYPE_INT3 = auto()
    LXR_TYPE_VEC2 = auto()
    LXR_TYPE_VEC3 = auto()
    
    LXR_DIRECTIVE_REQUIRECONTEXT = auto()
    LXR_DIRECTIVE_EXTENDS = auto()
    LXR_DIRECTIVE_INCLUDE = auto()
    LXR_DIRECTIVE_SETTING = auto()
    LXR_DIRECTIVE_COMMAND = auto()
    LXR_DIRECTIVE_CONST = auto()
    LXR_DIRECTIVE_STRUCT = auto()
    
    LXR_LOCAL_STRUCT = auto()
    LXR_LOCAL_INCLUDE = auto()
    
    LXR_COMMA = auto()
    LXR_SEMICOLON = auto()
    LXR_COLON = auto()
    LXR_DOUBLE_COLON = auto()
    LXR_DOT = auto()
    LXR_ARROW = auto()
    LXR_TRIPLE_PLUS = auto()
    LXR_TRIPLE_MINUS = auto()
    LXR_TRIPLE_ASTERISK = auto()
    
    LXR_OPERATOR_ADD = auto()
    LXR_OPERATOR_SUB = auto()
    LXR_OPERATOR_TIMES = auto()
    LXR_OPERATOR_DIV = auto()
    LXR_OPERATOR_MOD = auto()
    LXR_OPERATOR_TEXT_JOIN = auto()
    LXR_OPERATOR_EQUAL = auto()
    LXR_OPERATOR_NOT_EQUAL = auto()
    LXR_OPERATOR_NOT = auto()
    LXR_OPERATOR_GREATER = auto()
    LXR_OPERATOR_GREATER_EQUAL = auto()
    LXR_OPERATOR_LOWER = auto()
    LXR_OPERATOR_LOWER_EQUAL = auto()
    LXR_OPERATOR_AND = auto()
    LXR_OPERATOR_OR = auto()
    
    LXR_STORAGE_NETREAD = auto()
    LXR_STORAGE_NETWRITE = auto()
    LXR_STORAGE_METADATA = auto()
    LXR_STORAGE_PERSISTENT = auto()
    
    LXR_ASSIGN_EQUAL = auto()
    LXR_ASSIGN_REF = auto()
    LXR_ASSIGN_ADD = auto()
    LXR_ASSIGN_SUB = auto()
    LXR_ASSIGN_TIMES = auto()
    LXR_ASSIGN_DIV = auto()
    LXR_ASSIGN_MOD = auto()
    LXR_ASSIGN_TEXT_JOIN = auto()
    
    LXR_UNKNOWN = auto()
    
    PRS_EXPRESSION = auto()
    PRS_EXPRESSION_LIST = auto()
    PRS_EXPRESSION_ARRAY_KEY_ELEM_LIST = auto()
    PRS_EXPRESSION_STRUCT_ASSIGN_LIST = auto()
    
    PRS_EXPRESSION_ACC = auto()
    PRS_EXPRESSION_NONACC = auto()
    
    PRS_EXPRESSION_INTERP_STRING = auto()
    
    PRS_STATEMENT = auto()
    PRS_STATEMENT_LIST = auto()
    PRS_BLOCK = auto()
    PRS_EMPTY_NEW_SCOPE = auto()
    PRS_EMPTY_OLD_SCOPE = auto()
    
    PRS_DECLARE_STORAGE = auto()
    PRS_DECLARE_TYPE = auto()
    PRS_DECLARE_AS = auto()
    PRS_DECLARE_FOR = auto()
    PRS_DECLARE_ASSIGN = auto()
    
    PRS_FOR_NEW_VALUE = auto()
    PRS_FOREACH_NEW_VALUES = auto()
    
    PRS_CASE_LIST = auto()
    PRS_CASETYPE_LIST = auto()
    PRS_CASE = auto()
    PRS_CASETYPE = auto()
    PRS_DEFAULT = auto()
    
    PRS_NAMESPACE = auto()
    PRS_CLASS_NAMESPACE = auto()
    
    PRS_TYPE = auto()
    PRS_CLASS_LIST = auto()
    
    PRS_GLOBAL_DEFINITION = auto()
    PRS_GLOBAL_DEFINITION_LIST = auto()
    PRS_FUNCDEF_NEW = auto()
    PRS_FUNCDEF_ARGS = auto()
    
    PRS_LITERAL = auto()
    PRS_LITERAL_LIST = auto()
    PRS_LITERAL_ARRAY_KEY_ELEM_LIST = auto()
    PRS_LITERAL_STRUCT_ASSIGN_LIST = auto()
    
    PRS_DIRECTIVE = auto()
    PRS_DIRECTIVE_LIST = auto()
    PRS_DIRECTIVE_STRUCT_ARGS = auto()
    
    PRS_MAIN = auto()
    PRS_PROG = auto()
    
    PRS_EMPTY = auto()
    
    PRC_OPERATOR_UMINUS = auto()
    PRC_OPERATOR_UNOT = auto()
    PRC_IF = auto()

    def is_lexer (self):          return self.name.startswith('LXR')
    def is_parser (self):         return self.name.startswith('PRS')
    def is_precedence (self):     return self.name.startswith('PRC')
    def is_empty (self):          return self.name.startswith('PRS_EMPTY')
    def is_lexer_ignored (self):  return self in [TokenType.LXR_WHITESPACE]
    def is_parser_ignored (self): return self in [TokenType.LXR_COMMENT]